In [1]:
import numpy as np 
x=np.arange(8)
y = np.arange(1,9)
np.sum(x)

28

In [4]:
np.mean(x
       )


3.5

In [7]:
np.std(x)

2.29128784747792

In [8]:
np.min(x)

0

In [9]:
np.max(x)

7

In [11]:
np.prod(y)

40320

In [12]:
np.cumsum(x)

array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [14]:
np.cumprod(y)

array([    1,     2,     6,    24,   120,   720,  5040, 40320])

In [16]:
np.median(x)

3.5

In [17]:
np.exp(x)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03])